import { cn } from './cn';

/**
 * A plain <img> with the guarantees the specification asks for:
 *
 *  - `alt` is required by the type, so an image cannot be rendered without it
 *    (FR-MED-5, NFR-A11Y-4). Decorative images pass `alt=""` explicitly.
 *  - `width` and `height` are required, so the box is reserved before the
 *    bytes arrive and nothing shifts (FR-MED-6, NFR-PERF-2).
 *  - Anything below the fold lazy-loads by default; `priority` opts a single
 *    above-the-fold image out.
 *
 * `srcSet`/`sizes` are passed straight through — the responsive derivatives in
 * FR-MED-4 are generated by the media pipeline, not decided here.
 */
export type ImageFit = 'cover' | 'contain';
export type ImageRadius = 'none' | 'sm' | 'md' | 'lg' | 'full';

const FIT: Record<ImageFit, string> = {
  cover: 'object-cover',
  contain: 'object-contain',
};

const RADIUS: Record<ImageRadius, string> = {
  none: 'rounded-none',
  sm: 'rounded-sm',
  md: 'rounded-md',
  lg: 'rounded-lg',
  full: 'rounded-full',
};

export interface ImageProps {
  src: string;
  /** Required. Pass an empty string only for genuinely decorative images. */
  alt: string;
  width: number;
  height: number;
  srcSet?: string;
  sizes?: string;
  fit?: ImageFit;
  radius?: ImageRadius;
  /** Above the fold: loads eagerly and is decoded synchronously. */
  priority?: boolean;
  className?: string;
}

export function Image({
  src,
  alt,
  width,
  height,
  srcSet,
  sizes,
  fit = 'cover',
  radius = 'none',
  priority = false,
  className,
}: ImageProps) {
  return (
    <img
      src={src}
      alt={alt}
      width={width}
      height={height}
      srcSet={srcSet}
      sizes={sizes}
      loading={priority ? 'eager' : 'lazy'}
      decoding={priority ? 'sync' : 'async'}
      fetchPriority={priority ? 'high' : 'auto'}
      className={cn('block max-w-full h-auto', FIT[fit], RADIUS[radius], className)}
    />
  );
}
